POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY0BnbWFpbC5jb20iLCJleHAiOjE3MjAzNjIxNjksInVzZXJJZCI6Mn0._FcY3biPbwMGRG6qeacSyq2EWAQUo1gw1HhBWckffOo

{
  "name": "Test new event 2",
  "description": "A test new event",
  "location": "A test new location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}