POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiZDJAZ21haWwuY29tIiwiZXhwIjoxNzIxMDQ4ODc5LCJ1c2VySWQiOjF9.tWs4vLzxsWaB4_DncBQ2d3ufZ2k2Q602ekmDEqQ6OIg

{
  "name": "Test new event 2",
  "description": "A test new event",
  "location": "A test new location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}