POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY2RAZ21haWwuY29tIiwiZXhwIjoxNzIwMDIxMjAxLCJ1c2VySWQiOjF9.czRuhszn55049sDBt90oVdeBzurBFf8LfyZ_vi7C8IY

{
  "name": "Test new event 2",
  "description": "A test new event",
  "location": "A test new location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}