DELETE http://localhost:8080/events/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiZEBnbWFpbC5jb20iLCJleHAiOjE3MjAzNzg2MjksInVzZXJJZCI6NH0.ZWSaC1PAhyq2bfUwEp9PvR3gFi3rIZGD-wWXNTSt1WU